idle_bg = "#00000000"
idle_fg = "#d3d3d3"
info_bg = "#00000000"
info_fg = "#93a1a1"
good_bg = "#00000000"
good_fg = "#859900"
warning_bg  = "#00000000"
warning_fg  = "#b58900"
critical_bg = "#00000000"
critical_fg = "#dc322f"
separator = "   "
separator_bg = "#00000000"
separator_fg = "#a9a9a9"
alternating_tint_bg = "#00000000"